language: node_js
node_js:
  - "stable"
  - "0.10"
  - "iojs"
services:
  - mongodb
before_install: npm install bunyan nodemon mocha karma-cli bower jshint grunt-cli -g
install: npm install
before_script: cp config.sample.js config.js;cd frontend;grunt build;cd ..;
